### ISSUE TITLE
Nom de domaine

### ISSUE THREAD

**Issue by JulienBarnu** [SocialGouv/covid#6]
Réserver un nom de domaine pour la plateforme. Proposé : covid-19.sante.gouv.fr

**Comment by revolunet** [comment]
en cours côté Fabrique

**Comment by igorrenquin** [comment]
besoin d'une URL pour une API?

**Comment by igorrenquin** [comment]
Sur quelle plateforme avez vous prévu d'héberger le produit?
IaaS ou CaaS?

**Comment by revolunet** [comment]
K8s

**Comment by igorrenquin** [comment]
La demande de mise en place de la délégation vers Azure DNS pour les domaines:
- covid-19.sante.gouv.fr
- covid19.sante.gouv.fr

En attente de réalisation

Pour chacun des domaines les entrèes suivantes ont été mise en place:
- *. vers plateforme K8s PROD
- @ vers plateforme K8s PROD
- www. vers plateforme K8s PROD

**Comment by igorrenquin** [comment]
covid-19.sante.gouv.fr  renvoi vers notre plateforme

**Comment by igorrenquin** [comment]
covid19.sante.gouv.fr renvoi vers notre plateforme
